# Import


In [1]:
# !pip install ipympl
# !pip3 install roboticstoolbox-python
%matplotlib widget
# PyTorch
import torch
import torch.nn as nn
from torch.optim import optimizer

# For data preprocess
import numpy as np
import csv
import os

# For plotting
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure

from roboticstoolbox import DHRobot, RevoluteMDH 
import math

# GPU infomation


In [2]:
GPU_name = torch.cuda.get_device_name()
print(GPU_name)

NVIDIA GeForce GTX 1050


# Utilities

In [3]:
def get_device():
    ''' Get device (if GPU is available, use GPU) '''
    return 'cuda' if torch.cuda.is_available() else 'cpu'

def plot_learning_curve(loss_record, title=''):
    ''' Plot learning curve of your DNN (train & dev loss) '''
    total_steps = len(loss_record['train'])
    x_1 = range(total_steps)
    # x_2 = x_1[::len(loss_record['train']) // len(loss_record['dev'])]
    x_2 = range(total_steps)
    figure(figsize=(6, 4))
    plt.plot(x_1, loss_record['train'], c='tab:red', label='train')
    plt.plot(x_2, loss_record['dev'], c='tab:cyan', label='dev')
    plt.ylim(0.0, 1.)
    plt.xlabel('Training steps')
    plt.ylabel('MSE loss')
    plt.title('Learning curve of {}'.format(title))
    plt.legend()
    plt.show()

# Network


In [4]:
class NeuralNet(nn.Module):
    ''' A neural network '''
    def __init__(self, input_dim, output_dim):
        super(NeuralNet, self).__init__()

        # Define your neural network here
        # TODO: How to modify this model to achieve better performance?
        self.net = nn.Sequential(
            nn.Linear(input_dim, 32),
            nn.Sigmoid(),
            nn.Linear(32, 64),
            nn.RReLU(),
            nn.Linear(64, 32),
            nn.LeakyReLU(),
            nn.Linear(32, output_dim)
        )

        # Mean squared error loss
        self.criterion = nn.MSELoss(reduction='mean')

    def forward(self, x):
        ''' Given input of size (batch_size x input_dim), compute output of the network '''
        return self.net(x)

    def cal_loss(self, pred, target):
        ''' Calculate loss '''
        # def euclidean_distance(y_true, y_pred):
        # return kr.sqrt(kr.sum(kr.square(y_true - y_pred)))
        return self.criterion(pred, target)

# 宣告Dobot位置與軸關節公式函數(順向運動學)


In [5]:
def dobot_forword_kine(joints):

    if joints.ndim == 1:
        joints = np.expand_dims(joints, 0)

    q1 = joints[:, 0:1] # 0:1而非直接0->確保內部採用Column處理
    q2 = joints[:, 1:2]
    q3 = joints[:, 2:3]

    a2 = 135
    a3 = 147
    a4 = 61

    C1 = np.cos(q1)
    C2 = np.cos(q2)
    C23 = np.cos(q2 + q3)
    S1 = np.sin(q1)
    S2 = np.sin(q2)
    S23 = np.sin(q2 + q3)

    dx = C1 * (a3 * C23 + a2 * C2 + a4)
    dy = S1 * (a3 * C23 + a2 * C2 + a4)
    dz = -a2 * S2 - a3 * S23	

    Point = np.hstack([dx, dy, dz]) # 建立陣列
    return Point

# 產生訓練集資料

In [6]:
def gen_data(Train_num):
    joint_1 = (-np.pi / 2) + np.pi * np.random.rand(Train_num, 1)
    joint_2 = (-85 * np.pi / 180) + (85 * np.pi / 180) * np.random.rand(Train_num, 1)
    joint_3 = (-10 * np.pi / 180) + (105 * np.pi / 180) * np.random.rand(Train_num, 1)
    joints = np.hstack((joint_1, joint_2, joint_3))
    points = dobot_forword_kine(joints)
    return points, joints

In [7]:
x_train, y_train = gen_data(10000)
x_dev, y_dev = gen_data(500)

# Dev Func


In [8]:
def dev(feature_dev,target_dev, model, device):
    model.eval()                                # set model to evalutation mode
    with torch.no_grad():                   # disable gradient calculation
        pred = model(feature_dev)                     # forward pass (compute output)
        mse_loss = model.cal_loss(pred, target_dev)  # compute loss
    return mse_loss

# Train Setup

In [9]:
# Ref: https://ithelp.ithome.com.tw/articles/10276281

# 0) prepare data

feature = torch.from_numpy(x_train)
print(feature.size())
target = torch.from_numpy(y_train)
print(target.size())

feature_dev = torch.from_numpy(x_dev)
target_dev = torch.from_numpy(y_dev)

feature,target=feature.type(torch.FloatTensor),target.type(torch.FloatTensor)
feature_dev,target_dev=feature_dev.type(torch.FloatTensor),target_dev.type(torch.FloatTensor)


n_samples, n_features = feature.shape
print(n_samples)
print(n_features)

# 1) model
model = NeuralNet(n_features, n_features)
# 2) loss and optimizer
learning_rate = 0.001
# optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

# 3) training loop
epochs = 10000
min_mse = 1000.0
os.makedirs('models', exist_ok=True)
device = get_device()                 # get the current available device ('cpu' or 'cuda')
loss_record = {'train': [], 'dev': []} 

torch.Size([10000, 3])
torch.Size([10000, 3])
10000
3


# Training Loop

In [10]:
for epoch in range(epochs):
    model.train()
    # forward pass and loss
    y_predicted = model(feature)
    # print(y_predicted)
    # loss = criterion(y_predicted, target)
    mse_loss = model.cal_loss(y_predicted, target)

    # backward pass
    mse_loss.backward()


    # update
    optimizer.step()
    loss_record['train'].append(mse_loss.detach().cpu().item())

    dev_mse = dev(feature_dev,target_dev, model, device)
    loss_record['dev'].append(dev_mse)

    # init optimizer
    optimizer.zero_grad()

    if (epoch + 1) % 10 == 0:
        print(f'epoch: {epoch+1}, dev_loss = {dev_mse.item(): .4f}')
        if (dev_mse < min_mse):
            torch.save(model.state_dict(), 'models/model.pth')
            min_mse = dev_mse
            print('Saving model (epoch = {:4d}, train_loss = {:.4f}, dev_loss = {:.4f})'
                    .format(epoch + 1, mse_loss, dev_mse))
            

print('Finished training after {} epochs'.format(epoch+1))

epoch: 10, dev_loss =  0.5049
Saving model (epoch =   10, train_loss = 0.5082, dev_loss = 0.5049)
epoch: 20, dev_loss =  0.3238
Saving model (epoch =   20, train_loss = 0.3192, dev_loss = 0.3238)
epoch: 30, dev_loss =  0.2213
Saving model (epoch =   30, train_loss = 0.2211, dev_loss = 0.2213)
epoch: 40, dev_loss =  0.1479
Saving model (epoch =   40, train_loss = 0.1459, dev_loss = 0.1479)
epoch: 50, dev_loss =  0.1240
Saving model (epoch =   50, train_loss = 0.1210, dev_loss = 0.1240)
epoch: 60, dev_loss =  0.1080
Saving model (epoch =   60, train_loss = 0.1060, dev_loss = 0.1080)
epoch: 70, dev_loss =  0.0996
Saving model (epoch =   70, train_loss = 0.0974, dev_loss = 0.0996)
epoch: 80, dev_loss =  0.0962
Saving model (epoch =   80, train_loss = 0.0948, dev_loss = 0.0962)
epoch: 90, dev_loss =  0.0936
Saving model (epoch =   90, train_loss = 0.0919, dev_loss = 0.0936)
epoch: 100, dev_loss =  0.0920
Saving model (epoch =  100, train_loss = 0.0905, dev_loss = 0.0920)
epoch: 110, dev_los

# Test

In [11]:
# generate test data
# in this problem, the test set is not completely unknown, so I print it out and even calculate the loss
x_test, y_test = gen_data(20)
test_feature = torch.from_numpy(x_test)
test_target = torch.from_numpy(y_test)
test_feature,test_target=test_feature.type(torch.FloatTensor),test_target.type(torch.FloatTensor)
n_samples, n_features = test_feature.shape

In [21]:
del model
model = NeuralNet(n_features, n_features).to(device)
ckpt = torch.load('models/model.pth', map_location='cpu')  # Load your best model
model.load_state_dict(ckpt)

<All keys matched successfully>

In [23]:
model.eval()   
test_feature = test_feature.to(device) 
test_target = test_target.to(device)                             # set model to evalutation mode
with torch.no_grad():                   # disable gradient calculation
    pred = model(test_feature)                     # forward pass (compute output)
# print("test_feature: ")
# print(test_feature)
print("y_pred: ")
print(pred)
print("y_test: ")
print(test_target)
print("test MSE loss: ")
test_loss = model.cal_loss(pred, test_target)
print(test_loss)

y_pred: 
tensor([[ 1.3450, -0.0846,  0.5490],
        [-0.8396, -0.2975,  1.2422],
        [-1.3522, -0.4972,  1.5437],
        [ 0.0836, -1.2533,  0.2640],
        [ 0.8886, -0.1301,  0.8377],
        [-0.5215, -0.5346,  0.2807],
        [-1.3879, -0.4244,  0.5324],
        [-1.3809, -0.7392,  0.8559],
        [ 1.0974, -0.4056,  0.2412],
        [ 1.0149, -1.4008,  0.3432],
        [-0.2835, -0.7196,  0.2229],
        [-0.8126, -0.6941,  0.1572],
        [-1.5457, -0.0998,  0.9279],
        [ 1.0318, -1.1195,  0.5527],
        [ 0.8403, -0.2079,  0.4610],
        [-0.7921, -0.8839,  0.1485],
        [-0.4656, -1.3830,  0.9554],
        [-0.9465, -0.8630,  0.6338],
        [ 1.0773, -1.2645,  0.2091],
        [-0.8342, -0.5121,  0.3046]], device='cuda:0')
y_test: 
tensor([[ 1.3371, -0.1332,  0.5526],
        [-0.8379, -0.3272,  1.3089],
        [-1.3759, -0.5166,  1.5784],
        [ 0.1031, -1.1938,  0.1979],
        [ 0.9131, -0.0859,  0.8004],
        [-0.4969, -0.4854,  0.1739],
  

# Visualization

In [17]:
plot_learning_curve(loss_record, title='deep model')
# the learning curve of dev and train overlaps since this problem is simple

FigureCanvasNbAgg()

# Robot Arm

In [18]:
# DH ref: https://forum.dobot.cc/t/dobot-magicain-kinematics/3305
# Scale down 1/1000 to fit in the plot
class DOBOT(DHRobot):
    def __init__(self):
        super().__init__(
                [
                    RevoluteMDH(),
                    RevoluteMDH(alpha=np.pi/2),
                    RevoluteMDH(a=0.135),
                    RevoluteMDH(a=0.147),
                    RevoluteMDH(a=0.061),
                ], name="DOBOT")        

In [19]:
robot = DOBOT()
print(robot)
test = [0 ,0 ,0, 0, 0]
robot.plot(test)


DHRobot: DOBOT, 5 joints (RRRRR), dynamics, modified DH parameters
┏━━━━━━┳━━━━━━━┳━━━━━┳━━━━━┓
┃aⱼ₋₁  ┃ ⍺ⱼ₋₁  ┃ θⱼ  ┃ dⱼ  ┃
┣━━━━━━╋━━━━━━━╋━━━━━╋━━━━━┫
┃  0.0 ┃  0.0° ┃  q1 ┃ 0.0 ┃
┃  0.0 ┃ 90.0° ┃  q2 ┃ 0.0 ┃
┃0.135 ┃  0.0° ┃  q3 ┃ 0.0 ┃
┃0.147 ┃  0.0° ┃  q4 ┃ 0.0 ┃
┃0.061 ┃  0.0° ┃  q5 ┃ 0.0 ┃
┗━━━━━━┻━━━━━━━┻━━━━━┻━━━━━┛



FigureCanvasNbAgg()

PyPlot3D backend, t = 0.05, scene:
  DOBOT

In [24]:
arr = pred[1].cpu().detach().numpy()
if(abs(arr[2])>abs(arr[1])):
    t4 = np.sign(arr[1]) * (abs(arr[2])-abs(arr[1]))
else:
    t4 =  np.sign(arr[2]) * (abs(arr[1])-abs(arr[2]))

print('pred')
print(arr)
print('')

print('target')
print(test_target[1])
print('')

arr = np.append(arr, np.array([t4,0]), axis=0)

print('joint config')
print(arr)
print('')

T = robot.fkine(arr)
print(T)
# sol = robot.ikine_LM(T)
# print(sol)
# print('')
print("X Y Z")
print(test_feature[1])
print('')
robot.plot(arr)

pred
[-0.8395937  -0.29749826  1.2422378 ]

target
tensor([-0.8379, -0.3272,  1.3089], device='cuda:0')

joint config
[-0.83959371 -0.29749826  1.24223781 -0.94473958  0.        ]

   0.6678    1.99e-08 -0.7444    0.1844    
  -0.7444   -2.218e-08 -0.6678   -0.2056    
  -2.98e-08  1         0         0.07955   
   0         0         0         1         

X Y Z
tensor([ 180.9824, -201.0605,  -78.8292], device='cuda:0')



PyPlot3D backend, t = 0.05, scene:
  DOBOT